# Meicho Minutes Configuration File
# 名著1分動画生成システムの設定ファイル

# VoiceVox TTS 設定
voicevox:
  base_url: "http://127.0.0.1:50021"
  default_speaker: 1
  request_timeout: 30
  retry_attempts: 3
  retry_delay: 1.0

# Gemini Script Generator 設定
gemini:
  model: "gemini-1.5-flash"
  # API_KEY は環境変数 GEMINI_API_KEY から読み込み
  temperature: 0.7
  max_output_tokens: 1000
  request_timeout: 30
  retry_attempts: 3

# Amazon Scraper 設定
amazon:
  request_delay: 1.0
  max_retries: 3
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

# 動画生成設定と字幕設定は src/video_generator.py にハードコーディング
# (設定変更は video_generator.py の DEFAULT_SETTINGS を編集)

# ファイル管理設定
files:
  temp_dir: "/tmp"
  output_dir: "./output"
  intermediate_files:
    keep_on_success: false
    keep_on_error: true
  max_file_age_hours: 24

# ログ設定
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: "./logs/meicho_minutes.log"
  console_enabled: true

# 実験的機能
experimental:
  parallel_processing: false
  gpu_acceleration: false
  cache_enabled: true
  cache_ttl_hours: 24

# デバッグ設定
debug:
  save_intermediate_files: false
  verbose_output: false
  performance_monitoring: false